"""ResearchState — Pydantic BaseModel for the LangGraph research pipeline.

GDPR rules:
- original_question content must never appear in logs.
- final_answer and citations content must never appear in logs.
- retrieved_chunks text (highlight_text) must never appear in logs.
- iterations[*].reasoning must never appear in logs.
"""

from __future__ import annotations

from typing import Any
from uuid import UUID

from pydantic import BaseModel, Field


class ResearchIteration(BaseModel):
    """Working memory for a single research iteration.

    Each iteration corresponds to one planning → retrieve cycle.
    """

    step: int
    query: str  # the sub-query generated by node_research_plan for this iteration
    retrieved_chunks: list[dict[str, Any]] = Field(default_factory=list)
    reasoning: str  # LLM reasoning about what was found and what is still missing
    sufficient: bool  # LLM decision: is there enough evidence to answer now?


class ResearchState(BaseModel):
    """Shared state for the research graph pipeline.

    Identity fields are injected by ChatService and never mutated by nodes.
    Working-memory fields are accumulated across iterations.
    Output fields are set by node_research_synthesize.
    """

    # Identity — injected by ChatService, never mutated
    original_question: str
    pipeline_id: UUID
    tenant_id: UUID
    collection_ids: list[UUID]
    allowed_collection_ids: list[UUID]
    llm_model_id: UUID
    conversation_history: list[dict[str, str]] = Field(default_factory=list)
    max_steps: int = 3  # step budget cap; configurable via pipeline prompt_config

    # Working memory — accumulated across iterations
    iterations: list[ResearchIteration] = Field(default_factory=list)
    all_retrieved_chunks: list[dict[str, Any]] = Field(default_factory=list)

    # Output — set by node_research_synthesize
    final_answer: str = ""
    citations: list[dict[str, Any]] = Field(default_factory=list)
    steps_taken: int = 0
    prompt_tokens: int = 0
    completion_tokens: int = 0
