"""OnboardingService — stateful 5-step tenant onboarding wizard.

All methods are idempotent: repeating a step with the same data is safe (upsert semantics).
Step 5 (activate) is the only irreversible step.

Security:
- All operations require platform:admin role (enforced by router dependency).
- tenant_id for new tenants is generated by the DB — never from request body.
- Resource creation is audited via audit_log after step 5 (activation).
- Expired sessions are rejected; status 'abandoned' sessions raise NotFoundError.
"""

from __future__ import annotations

import uuid
from datetime import UTC, datetime, timedelta
from typing import Any

import structlog
from sqlalchemy import select, update
from sqlalchemy.ext.asyncio import AsyncSession

from src.api.schemas.onboarding import (
    ActivationResultResponse,
    SessionStatusResponse,
    Step1TenantConfigRequest,
    Step2CollectionsRequest,
    Step3AdminUserRequest,
    Step4PipelineRequest,
    StepResultResponse,
)
from src.core.exceptions import ConflictError, DomainValidationError, NotFoundError
from src.db.models.onboarding_session import OnboardingSession
from src.db.repositories.tenant_repository import TenantRepository

logger = structlog.get_logger(__name__)

_SESSION_TTL_DAYS = 7
_STEPS_TOTAL = 5


def _utcnow() -> datetime:
    return datetime.now(UTC)


class OnboardingService:
    def __init__(self, session: AsyncSession) -> None:
        self._session = session

    # ── Session management ────────────────────────────────────────────────────

    async def create_session(
        self,
        platform_admin_id: uuid.UUID,
        tenant_name: str,
        tenant_slug: str,
        contact_email: str,
    ) -> OnboardingSession:
        """Start a new onboarding session (step 0 — no tenant created yet)."""
        now = _utcnow()
        session_obj = OnboardingSession(
            status="in_progress",
            current_step=0,
            steps_completed={},
            draft_config={
                "tenant_name": tenant_name,
                "tenant_slug": tenant_slug,
                "contact_email": contact_email,
            },
            created_by=platform_admin_id,
            created_at=now,
            updated_at=now,
            expires_at=now + timedelta(days=_SESSION_TTL_DAYS),
        )
        self._session.add(session_obj)
        await self._session.flush()
        logger.info("onboarding_session.created", session_id=str(session_obj.id))
        return session_obj

    async def get_session(self, session_id: uuid.UUID) -> OnboardingSession:
        """Fetch session; raise NotFoundError if missing/abandoned/expired."""
        obj = await self._session.get(OnboardingSession, session_id)
        if obj is None or obj.status == "abandoned":
            raise NotFoundError(f"Onboarding session {session_id} not found")
        if obj.expires_at < _utcnow():
            # Auto-abandon expired sessions on access
            await self._session.execute(
                update(OnboardingSession)
                .where(OnboardingSession.id == session_id)
                .values(status="abandoned", updated_at=_utcnow())
            )
            await self._session.flush()
            raise NotFoundError(f"Onboarding session {session_id} has expired")
        return obj

    async def abandon_session(self, session_id: uuid.UUID) -> None:
        obj = await self.get_session(session_id)
        if obj.status == "completed":
            raise ConflictError("Cannot abandon a completed onboarding session")
        await self._session.execute(
            update(OnboardingSession)
            .where(OnboardingSession.id == session_id)
            .values(status="abandoned", updated_at=_utcnow())
        )

    def _session_to_status(self, obj: OnboardingSession) -> SessionStatusResponse:
        next_step = obj.current_step + 1 if obj.current_step < _STEPS_TOTAL else None
        next_url = f"/api/v1/platform/onboarding/sessions/{obj.id}/steps/{next_step}" if next_step else None
        return SessionStatusResponse(
            session_id=obj.id,
            tenant_id=obj.tenant_id,
            status=obj.status,
            current_step=obj.current_step,
            steps_completed={k: bool(v) for k, v in obj.steps_completed.items()},
            expires_at=obj.expires_at,
            next_step_url=next_url,
        )

    # ── Step execution ────────────────────────────────────────────────────────

    async def execute_step_1(
        self, session_id: uuid.UUID, body: Step1TenantConfigRequest
    ) -> StepResultResponse:
        """Create or update the tenant record."""
        obj = await self.get_session(session_id)
        tenant_repo = TenantRepository(self._session)

        slug = obj.draft_config.get("tenant_slug", "")
        existing = await tenant_repo.get_by_slug(slug)
        if existing is not None and obj.tenant_id is None:
            raise ConflictError(f"Tenant with slug '{slug}' already exists")

        if obj.tenant_id is None:
            # Create tenant — not yet active (is_active handled at step 5)
            tenant = await tenant_repo.create(
                name=body.display_name,
                slug=slug,
                settings=body.settings,
            )
            await self._session.execute(
                update(OnboardingSession)
                .where(OnboardingSession.id == session_id)
                .values(tenant_id=tenant.id)
            )
        else:
            # Idempotent update
            tenant = await tenant_repo.get_by_id(obj.tenant_id)
            if tenant is None:
                raise NotFoundError("Tenant not found")
            await tenant_repo.update(tenant, name=body.display_name, settings=body.settings)

        await self._mark_step_complete(obj, step=1, extra_config={"display_name": body.display_name})
        return StepResultResponse(
            session_id=session_id, step_completed=1, next_step=2,
            message="Tenant configuration saved."
        )

    async def execute_step_2(
        self, session_id: uuid.UUID, body: Step2CollectionsRequest
    ) -> StepResultResponse:
        """Create collections for the tenant."""
        obj = await self.get_session(session_id)
        if not obj.steps_completed.get("1"):
            raise DomainValidationError("Step 1 (tenant configuration) must be completed first")

        from src.db.models.collection import Collection
        from src.db.models.models_registry import ModelsRegistry

        # Find default embedding model
        model_q = select(ModelsRegistry).limit(1)
        model = (await self._session.execute(model_q)).scalar_one_or_none()
        if model is None:
            raise DomainValidationError("No embedding model registered; cannot create collections")

        tenant_id = obj.tenant_id
        created_names = []
        for col_cfg in body.collections:
            existing_q = select(Collection).where(
                Collection.tenant_id == tenant_id,
                Collection.name == col_cfg.name,
            )
            existing = (await self._session.execute(existing_q)).scalar_one_or_none()
            if existing is not None:
                # Idempotent: update config
                existing.description = col_cfg.description
                existing.chunk_config = {
                    "strategy": col_cfg.chunk_strategy,
                    "chunk_size": col_cfg.chunk_size,
                    "overlap": col_cfg.chunk_overlap,
                    "primary_language": col_cfg.primary_language,
                }
            else:
                self._session.add(Collection(
                    tenant_id=tenant_id,
                    name=col_cfg.name,
                    description=col_cfg.description,
                    embedding_model_id=model.id,
                    chunk_config={
                        "strategy": col_cfg.chunk_strategy,
                        "chunk_size": col_cfg.chunk_size,
                        "overlap": col_cfg.chunk_overlap,
                        "primary_language": col_cfg.primary_language,
                    },
                ))
            created_names.append(col_cfg.name)

        await self._mark_step_complete(obj, step=2, extra_config={"collections": created_names})
        return StepResultResponse(
            session_id=session_id, step_completed=2, next_step=3,
            message=f"{len(created_names)} collection(s) configured."
        )

    async def execute_step_3(
        self, session_id: uuid.UUID, body: Step3AdminUserRequest
    ) -> StepResultResponse:
        """Assign initial admin user to the tenant."""
        obj = await self.get_session(session_id)
        if not obj.steps_completed.get("2"):
            raise DomainValidationError("Step 2 (collections) must be completed first")

        from src.db.models.user import User

        tenant_repo = TenantRepository(self._session)

        # Find or create user by keycloak_sub
        user = await tenant_repo.find_user_by_keycloak_sub(body.keycloak_user_id)
        if user is None:
            user = User(
                keycloak_sub=body.keycloak_user_id,
                email=body.email,
                display_name=body.display_name,
            )
            self._session.add(user)
            await self._session.flush()

        tenant_id = obj.tenant_id
        # Add user to tenant (idempotent — ConflictError swallowed)
        try:
            await tenant_repo.add_user(tenant_id, user.id)
        except ConflictError:
            pass  # already a member — idempotent

        await tenant_repo.assign_role(tenant_id, user.id, body.role)
        await self._mark_step_complete(obj, step=3, extra_config={"admin_user_id": str(user.id)})
        return StepResultResponse(
            session_id=session_id, step_completed=3, next_step=4,
            message="Admin user assigned."
        )

    async def execute_step_4(
        self, session_id: uuid.UUID, body: Step4PipelineRequest
    ) -> StepResultResponse:
        """Create the default RAG pipeline for the tenant."""
        obj = await self.get_session(session_id)
        if not obj.steps_completed.get("3"):
            raise DomainValidationError("Step 3 (admin user) must be completed first")

        from src.db.models.pipeline import Pipeline

        tenant_id = obj.tenant_id
        pipeline_q = select(Pipeline).where(
            Pipeline.tenant_id == tenant_id,
            Pipeline.name == body.pipeline_name,
        )
        pipeline = (await self._session.execute(pipeline_q)).scalar_one_or_none()
        pipeline_config = {
            "top_k": body.top_k,
            "score_threshold": body.score_threshold,
            "cache_responses": body.cache_responses,
            "guardrails_enabled": body.guardrails_enabled,
        }
        if pipeline is None:
            self._session.add(Pipeline(
                tenant_id=tenant_id,
                name=body.pipeline_name,
                config=pipeline_config,
                is_active=True,
            ))
        else:
            pipeline.config = pipeline_config

        await self._mark_step_complete(obj, step=4, extra_config={"pipeline_name": body.pipeline_name})
        return StepResultResponse(
            session_id=session_id, step_completed=4, next_step=5,
            message="Pipeline configured."
        )

    async def activate(self, session_id: uuid.UUID) -> ActivationResultResponse:
        """Step 5 — validate all steps complete and activate the tenant."""
        obj = await self.get_session(session_id)
        required = {"1", "2", "3", "4"}
        missing = required - set(str(k) for k, v in obj.steps_completed.items() if v)
        if missing:
            raise DomainValidationError(
                f"Cannot activate: steps {sorted(missing)} not completed"
            )

        from src.db.models.collection import Collection
        from src.db.models.pipeline import Pipeline
        from src.db.models.tenant import Tenant

        tenant = await self._session.get(Tenant, obj.tenant_id)
        if tenant is None:
            raise NotFoundError("Tenant not found")

        # Count created resources for response
        col_count = (
            await self._session.execute(
                select(Collection).where(Collection.tenant_id == obj.tenant_id)
            )
        ).scalars().all()
        pipeline_exists = (
            await self._session.execute(
                select(Pipeline).where(Pipeline.tenant_id == obj.tenant_id)
            )
        ).scalar_one_or_none() is not None

        now = _utcnow()
        await self._session.execute(
            update(OnboardingSession)
            .where(OnboardingSession.id == session_id)
            .values(status="completed", completed_at=now, updated_at=now, current_step=5)
        )

        logger.info(
            "onboarding.tenant_activated",
            session_id=str(session_id),
            tenant_id=str(obj.tenant_id),
            tenant_slug=tenant.slug,
        )

        return ActivationResultResponse(
            tenant_id=tenant.id,
            tenant_slug=tenant.slug,
            collections_created=len(col_count),
            pipeline_created=pipeline_exists,
            admin_user_assigned=bool(obj.steps_completed.get("3")),
            activated_at=now,
        )

    # ── Internal helpers ──────────────────────────────────────────────────────

    async def _mark_step_complete(
        self,
        obj: OnboardingSession,
        step: int,
        extra_config: dict[str, Any] | None = None,
    ) -> None:
        new_completed = {**obj.steps_completed, str(step): True}
        new_config = {**obj.draft_config, **(extra_config or {})}
        now = _utcnow()
        await self._session.execute(
            update(OnboardingSession)
            .where(OnboardingSession.id == obj.id)
            .values(
                steps_completed=new_completed,
                draft_config=new_config,
                current_step=max(obj.current_step, step),
                updated_at=now,
            )
        )
        await self._session.flush()
